/**
 * UNIVERSO DE TICKERS — empresas-alvo da sincronização dinâmica.
 * A base curada estática já cobre as mega-caps; aqui ficam os tickers
 * que ENRIQUECEM o Raio-X quando o usuário liga as fontes dinâmicas.
 */

/** B3 — liquidez alta (uma única chamada batched na BRAPI cobre todos). */
export const B3_UNIVERSE: { ticker: string; nome: string; setor: string }[] = [
  { ticker: 'PETR4', nome: 'Petrobras PN', setor: 'Energia' },
  { ticker: 'PETR3', nome: 'Petrobras ON', setor: 'Energia' },
  { ticker: 'VALE3', nome: 'Vale ON', setor: 'Extrativa Mineral' },
  { ticker: 'ITUB4', nome: 'Itaú Unibanco PN', setor: 'Bancário / Portador de Juros' },
  { ticker: 'BBDC4', nome: 'Bradesco PN', setor: 'Bancário / Portador de Juros' },
  { ticker: 'BBAS3', nome: 'Banco do Brasil ON', setor: 'Bancário / Portador de Juros' },
  { ticker: 'SANB11', nome: 'Santander Brasil UNIT', setor: 'Bancário / Portador de Juros' },
  { ticker: 'BPAC11', nome: 'BTG Pactual UNIT', setor: 'Bancário / Portador de Juros' },
  { ticker: 'ABEV3', nome: 'Ambev ON', setor: 'Alimentos e Bebidas' },
  { ticker: 'JBSS3', nome: 'JBS ON', setor: 'Alimentos e Bebidas' },
  { ticker: 'BRFS3', nome: 'BRF ON', setor: 'Alimentos e Bebidas' },
  { ticker: 'MRFG3', nome: 'Marfrig ON', setor: 'Alimentos e Bebidas' },
  { ticker: 'SLCE3', nome: 'São Martinho ON', setor: 'Alimentos e Bebidas' },
  { ticker: 'GGBR4', nome: 'Gerdau PN', setor: 'Siderurgia' },
  { ticker: 'GOAU4', nome: 'Gerdau Metalúrgica PN', setor: 'Siderurgia' },
  { ticker: 'CSNA3', nome: 'CSN ON', setor: 'Siderurgia' },
  { ticker: 'USIM5', nome: 'Usiminas UNIT', setor: 'Siderurgia' },
  { ticker: 'SUZB3', nome: 'Suzano ON', setor: 'Celulose e Papel' },
  { ticker: 'KLBN11', nome: 'Klabin UNIT', setor: 'Celulose e Papel' },
  { ticker: 'WEGE3', nome: 'WEG ON', setor: 'Bens de Capital' },
  { ticker: 'EMBR3', nome: 'Embraer ON', setor: 'Aeroindústria' },
  { ticker: 'AZUL4', nome: 'Azul PN', setor: 'Aeroindústria' },
  { ticker: 'GOLL4', nome: 'Gol PN', setor: 'Aeroindústria' },
  { ticker: 'MGLU3', nome: 'Magazine Luiza ON', setor: 'Varejo' },
  { ticker: 'LREN3', nome: 'Lojas Renner ON', setor: 'Varejo' },
  { ticker: 'VIVA3', nome: 'Vivara ON', setor: 'Varejo' },
  { ticker: 'PETZ3', nome: 'Petz ON', setor: 'Varejo' },
  { ticker: 'ASAI3', nome: 'Assaí ON', setor: 'Varejo atacarejo' },
  { ticker: 'CRFB3', nome: 'Carrefour Brasil ON', setor: 'Varejo atacarejo' },
  { ticker: 'RADL3', nome: 'Raia Drogasil ON', setor: 'Varejo farmacêutico' },
  { ticker: 'GUAR3', nome: 'Guararapes ON', setor: 'Varejo' },
  { ticker: 'ARZZ6', nome: 'Arezzo UNIT', setor: 'Varejo' },
  { ticker: 'SOMA3', nome: 'Grupo Soma ON', setor: 'Varejo' },
  { ticker: 'VIVT3', nome: 'Telefônica Brasil ON', setor: 'Telecomunicações' },
  { ticker: 'TIMP3', nome: 'TIM PN', setor: 'Telecomunicações' },
  { ticker: 'RENT3', nome: 'Localiza ON', setor: 'Locação de veículos' },
  { ticker: 'MOVI3', nome: 'Movida ON', setor: 'Locação de veículos' },
  { ticker: 'NTCO3', nome: 'Natura &Co ON', setor: 'Cosméticos' },
  { ticker: 'UGPA3', nome: 'Ultrapar PN', setor: 'Energia' },
  { ticker: 'PRIO3', nome: 'PRIO ON', setor: 'Energia' },
  { ticker: 'RECV3', nome: 'PetroReconcavo ON', setor: 'Energia' },
  { ticker: 'RRRP3', nome: '3R Petroleum ON', setor: 'Energia' },
  { ticker: 'B3SA3', nome: 'B3 ON', setor: 'Infraestrutura de mercado' },
  { ticker: 'ELET3', nome: 'Eletrobras ON', setor: 'Energia' },
  { ticker: 'CMIG4', nome: 'Cemig PN', setor: 'Energia' },
  { ticker: 'EQTL3', nome: 'Equatorial PN', setor: 'Energia' },
  { ticker: 'CPFE3', nome: 'CPFL Energia ON', setor: 'Energia' },
  { ticker: 'NEOE3', nome: 'Neoenergia ON', setor: 'Energia' },
  { ticker: 'EGIE3', nome: 'Engie Brasil ON', setor: 'Energia' },
  { ticker: 'TAEE11', nome: 'Taesa UNIT', setor: 'Energia' },
  { ticker: 'LIGT3', nome: 'Light ON', setor: 'Energia' },
  { ticker: 'SBSP3', nome: 'Sabesp ON', setor: 'Saneamento' },
  { ticker: 'CYRE3', nome: 'Cyrela ON', setor: 'Construção Civil' },
  { ticker: 'MRVE3', nome: 'MRV ON', setor: 'Construção Civil' },
  { ticker: 'EZTC3', nome: 'EZTec ON', setor: 'Construção Civil' },
  { ticker: 'CURY3', nome: 'Cury ON', setor: 'Construção Civil' },
  { ticker: 'DIRR3', nome: 'Direcional ON', setor: 'Construção Civil' },
  { ticker: 'JHSF3', nome: 'JHSF ON', setor: 'Construção Civil' },
  { ticker: 'RAIL3', nome: 'Rumo ON', setor: 'Logística' },
  { ticker: 'MILS3', nome: 'Mills ON', setor: 'Logística' },
  { ticker: 'PSSA3', nome: 'Porto Seguro ON', setor: 'Seguros' },
  { ticker: 'CXSE3', nome: 'Caixa Seguridade ON', setor: 'Seguros' },
  { ticker: 'WIZS3', nome: 'Wiz ON', setor: 'Seguros' },
  { ticker: 'FLRY3', nome: 'Fleury ON', setor: 'Saúde' },
  { ticker: 'HAPV3', nome: 'Hapvida ON', setor: 'Saúde' },
  { ticker: 'QUAL3', nome: 'Qualicorp ON', setor: 'Saúde' },
  { ticker: 'SMFT3', nome: 'Smart Fit ON', setor: 'Educação' },
  { ticker: 'COGN3', nome: 'Cogna ON', setor: 'Educação' },
  { ticker: 'YDUQ3', nome: 'Yduqs ON', setor: 'Educação' },
  { ticker: 'CVCB3', nome: 'CVC ON', setor: 'Turismo' },
  { ticker: 'AGRO3', nome: 'BrasilAgro ON', setor: 'Agronegócio' },
  { ticker: 'TUPY3', nome: 'Tupy ON', setor: 'Bens de Capital' },
  { ticker: 'ROMI3', nome: 'Romi ON', setor: 'Bens de Capital' },
  { ticker: 'AERI3', nome: 'Aeris ON', setor: 'Bens de Capital' },
  { ticker: 'LEVE3', nome: 'Iochpe-Maxion ON', setor: 'Autopeças' },
  { ticker: 'RAPT4', nome: 'Randon PN', setor: 'Autopeças' },
  { ticker: 'FRAS3', nome: 'Fras-le ON', setor: 'Autopeças' },
]

/**
 * Globais extras para Alpha Vantage (fundamentais completos por ticker).
 * Ordem = prioridade: a cota gratuita (~25 req/dia) sincroniza do topo.
 */
export const GLOBAL_EXTRA_UNIVERSE: { ticker: string; setor: string }[] = [
  { ticker: 'BLK', setor: 'Gestora de ativos' },
  { ticker: 'GS', setor: 'Bancário portador de juros' },
  { ticker: 'MS', setor: 'Bancário portador de juros' },
  { ticker: 'BAC', setor: 'Bancário portador de juros' },
  { ticker: 'WFC', setor: 'Bancário portador de juros' },
  { ticker: 'C', setor: 'Bancário portador de juros' },
  { ticker: 'SCHW', setor: 'Corretora / Gestora' },
  { ticker: 'BX', setor: 'Private equity' },
  { ticker: 'KKR', setor: 'Private equity' },
  { ticker: 'SPGI', setor: 'Índices / Ratings' },
  { ticker: 'MSCI', setor: 'Índices / Ratings' },
  { ticker: 'ICE', setor: 'Infraestrutura de mercado' },
  { ticker: 'NDAQ', setor: 'Infraestrutura de mercado' },
  { ticker: 'LIN', setor: 'Gases industriais' },
  { ticker: 'HON', setor: 'Indústria / Infraestrutura' },
  { ticker: 'MMM', setor: 'Indústria / Infraestrutura' },
  { ticker: 'FDX', setor: 'Logística' },
  { ticker: 'GM', setor: 'Automotivo' },
  { ticker: 'F', setor: 'Automotivo' },
  { ticker: 'AMAT', setor: 'Semicondutores' },
  { ticker: 'LRCX', setor: 'Semicondutores' },
  { ticker: 'KLAC', setor: 'Semicondutores' },
  { ticker: 'NXPI', setor: 'Semicondutores (móvel)' },
  { ticker: 'ON', setor: 'Semicondutores' },
  { ticker: 'GLW', setor: 'Materiais / Fibra óptica' },
  { ticker: 'APH', setor: 'Conectores / Componentes' },
  { ticker: 'SYK', setor: 'Equipamentos médicos' },
  { ticker: 'ISRG', setor: 'Robótica cirúrgica' },
  { ticker: 'VRTX', setor: 'Farmacêutica' },
  { ticker: 'REGN', setor: 'Farmacêutica' },
  { ticker: 'MRNA', setor: 'Farmacêutica (biotecnologia)' },
  { ticker: 'WM', setor: 'Saneamento / Resíduos' },
  { ticker: 'CTAS', setor: 'Serviços empresariais' },
  { ticker: 'ADP', setor: 'Folha de pagamento / Serviços' },
  { ticker: 'ITW', setor: 'Indústria / Infraestrutura' },
  { ticker: 'UL', setor: 'Consumo básico' },
  { ticker: 'BUD', setor: 'Bebidas' },
  { ticker: 'DEO', setor: 'Bebidas (destilados)' },
  { ticker: 'FMX', setor: 'Consumo LatAm (FEMSA)' },
  { ticker: 'SE', setor: 'Plataformas / Games (SEA)' },
  { ticker: 'GRAB', setor: 'Plataforma de mobilidade (SEA)' },
  { ticker: 'INFY', setor: 'TI / Terceirização global' },
  { ticker: 'WIT', setor: 'TI / Terceirização global' },
  { ticker: 'IBN', setor: 'Bancário portador de juros' },
  { ticker: 'RELX', setor: 'Editoração / Dados' },
  { ticker: 'NIO', setor: 'Automotivo / EV' },
  { ticker: 'LI', setor: 'Automotivo / EV' },
  { ticker: 'XPEV', setor: 'Automotivo / EV' },
  { ticker: 'TCOM', setor: 'Plataforma de viagens' },
]
